### ISSUE TITLE
Only XML files being generated

### ISSUE THREAD

**Issue by RossComputerGuy** [Makman2/GCR_CMake#16]
```
compile_gresources(LAUNCHER_RESOURCES LAUNCHER_RES_C
        TYPE EMBED_C
        TARGET "launcher-res.c"
        PREFIX "/com/emberliteOS/launcher/"
        SOURCE_DIR "${CMAKE_SOURCE_DIR}"
        COMPRESS_ALL
        RESOURCES ${LAUNCHER_RESOURCES})
add_custom_target(launcher-resources DEPENDS ${LAUNCHER_RES_C})
```
This should output `launcher-res.c` right? Unless the documentation is wrong.

**Comment by Makman2** [comment]
Sorry for the late response, I haven't lately checked GitHub so much.

It has been a while since I last touched this repo (and especially CMake), but according to what I have written long ago, shouldn't it be like this?
- `LAUNCHER_RESOURCES` receives the `launcher-res.c`
- `LAUNCHER_RES_C` is going to be set to the resources xml-file, I guess in this case `launcher-res.xml`?

So it should work correctly if you replace your target rule with this I hope:
```
add_custom_target(launcher-resources DEPENDS ${LAUNCHER_RESOURCES})
```

**Comment by Makman2** [comment]
Ah, is this documented wrongly from my side? For me right now it is clear what is meant, but since I have written this package, I maybe should phrase it differently.

**Comment by Makman2** [comment]
If there are specific suggestions, feel free to reopen :smile:
